# Generated by Django 2.2.4 on 2019-08-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='asked_date',
            field=models.TimeField(auto_now=True),
        ),
    ]
