# Generated by Django 2.2.7 on 2019-11-12 19:46

from django.db import migrations, models
import django.db.models.deletion
import university.validators


class Migration(migrations.Migration):

    dependencies = [
        ('guidance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='applications_development_career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('potential_employers', models.CharField(max_length=30)),
                ('picture', models.ImageField(upload_to='university/careers/', validators=[university.validators.image_validation_extension])),
            ],
        ),
        migrations.CreateModel(
            name='Fields_of_study_or_course_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='multimedia_career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('potential_employers', models.CharField(max_length=30)),
                ('picture', models.ImageField(upload_to='university/careers/', validators=[university.validators.image_validation_extension])),
            ],
        ),
        migrations.CreateModel(
            name='network_communication_career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('potential_employers', models.CharField(max_length=30)),
                ('picture', models.ImageField(upload_to='university/careers/', validators=[university.validators.image_validation_extension])),
            ],
        ),
        migrations.CreateModel(
            name='minimum_admission_requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('subject_mark', models.IntegerField()),
                ('general_admission_requirement', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guidance.Fields_of_study_or_course_name')),
            ],
        ),
    ]
