# Generated by Django 2.2.4 on 2019-08-12 11:50

from django.db import migrations, models
import university.validators


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstFeautured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='university/feautured/', validators=[university.validators.image_validation_extension])),
                ('heading', models.CharField(max_length=300)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SecondFeautured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='university/feautured/', validators=[university.validators.image_validation_extension])),
                ('heading', models.CharField(max_length=300)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ThirdFeautured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='university/feautured/', validators=[university.validators.image_validation_extension])),
                ('heading', models.CharField(max_length=300)),
                ('content', models.TextField()),
            ],
        ),
    ]
