# Generated by Django 2.2.4 on 2019-08-12 12:48

from django.db import migrations, models
import university.validators


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_firstfeautured_secondfeautured_thirdfeautured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='home/feautured/', validators=[university.validators.image_validation_extension])),
                ('content', models.TextField()),
                ('buttonAction', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(upload_to='home/carousel/', validators=[university.validators.image_validation_extension]),
        ),
        migrations.AlterField(
            model_name='firstfeautured',
            name='image',
            field=models.ImageField(upload_to='home/feautured/', validators=[university.validators.image_validation_extension]),
        ),
        migrations.AlterField(
            model_name='secondfeautured',
            name='image',
            field=models.ImageField(upload_to='home/feautured/', validators=[university.validators.image_validation_extension]),
        ),
        migrations.AlterField(
            model_name='thirdfeautured',
            name='image',
            field=models.ImageField(upload_to='home/feautured/', validators=[university.validators.image_validation_extension]),
        ),
    ]
