# Generated by Django 2.2.4 on 2019-08-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190812_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdfeautured',
            name='sub_content',
            field=models.CharField(default='2018 news', max_length=300),
            preserve_default=False,
        ),
    ]
