# Generated by Django 2.2.4 on 2019-08-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_thirdfeautured_sub_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thirdfeautured',
            name='sub_content',
        ),
        migrations.AddField(
            model_name='headline',
            name='sub_content',
            field=models.CharField(default='kul', max_length=300),
            preserve_default=False,
        ),
    ]
