# Generated by Django 2.2.4 on 2019-08-12 12:48

from django.db import migrations, models
import university.validators


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='about/creators/', validators=[university.validators.image_validation_extension])),
                ('qualification', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
            ],
        ),
    ]
