# Generated by Django 2.2 on 2019-07-27 23:27

from django.db import migrations, models
import university.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='university/logo/', validators=[university.validators.image_validation_extension])),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('province', models.CharField(choices=[('Northern Cape', 'Northern Cape'), ('Eastern Cape', 'Eastern Cape'), ('Free State', 'Free State'), ('Western Cape', 'Western Cape'), ('Limpopo', 'Limpopo'), ('North West', 'North West'), ('KwaZulu-Natal', 'KwaZulu-Natal'), ('Mpumalanga', 'Mpumalanga'), ('Gauteng', 'Gauteng')], max_length=244)),
                ('physical_address', models.TextField()),
            ],
        ),
    ]
