# Generated by Django 2.2.4 on 2019-08-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.IntegerField()),
                ('emai', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('school_or_department', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='universityview',
            name='name',
            field=models.CharField(choices=[('University of Cape Town', 'University of Cape Town'), ('Walter Sisulu University', 'Walter Sisulu University'), ('University of Fort Hare', 'University of Fort Hare'), ('University of the Free State', 'University of the Free State'), ('University of KwaZulu-Natal', 'University of KwaZulu-Natal'), ('University of Limpopo', 'University of Limpopo'), ('North-West University', 'North-West University'), ('University of Pretoria', 'University of Pretoria'), ('Rhodes University', 'Rhodes University'), ('Sefako Makgatho University', 'Sefako Makgatho University'), ('University of Stellenbosch', 'University of Stellenbosch'), ('University of the Western Cape', 'University of the Western Cape'), ('University of the Witwatersrand', 'University of the Witwatersrand'), ('University of Johannesburg', 'University of Johannesburg'), ('Nelson Mandela University', 'Nelson Mandela University'), ('University of South Africa', 'University of South Africa'), ('University of Venda', 'University of Venda'), ('University of Zululand', 'University of Zululand'), ('Cape Peninsula University of Technology', 'Cape Peninsula University of Technology'), ('Central University of Technology', 'Central University of Technology'), ('Durban University of Technology', 'Durban University of Technology'), ('Mangosuthu University of Technology', 'Mangosuthu University of Technology'), ('University of Mpumalanga', 'University of Mpumalanga'), ('Tshwane University of Technology', 'Tshwane University of Technology'), ('Vaal University of Technology', 'Vaal University of Technology')], max_length=300),
        ),
    ]
